### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by aemelianoff** [netology-code/git-homeworks#2]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи 

#### Ожидаемый результат

Форма обратной связи не слишком сжата.

#### Фактический результат

Форма обратной связи слишком сжата. (см. скриншот)

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
