### ISSUE TITLE
Белый текст наезжает на белое изображение в мобильной версии сайта.

### ISSUE THREAD

**Issue by Saiferin** [netology-code/git-homeworks#20]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
3. Перейти в режим адаптива 400px и ниже до 320px

#### Ожидаемый результат

Текст не наезжает на изображение

#### Фактический результат

Текст наезжает на изображение (см. скриншот)

#### Программное окружение

* Устройство: Samsung A50 (Android 9)
* Браузер: Chrome Версия 86.0.4240.75 (Официальная сборка), (64 бит)

#### Скриншоты

![](https://i.imgur.com/HJ1VbMj.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
