### ISSUE TITLE
Главная страница. Текстовый блок "Оставайтесь на связи" не правильно переносится

### ISSUE THREAD

**Issue by Saiferin** [netology-code/git-homeworks#21]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
3. Перейти в режим мобильная версия 400px и ниже до 320px

#### Ожидаемый результат

Текст слово "Оставайтесь" не переносится на следующую строку

#### Фактический результат

Текст переносится на следующую строку (см. скриншот)

#### Программное окружение

* Устройство: Samsung A50 (Android 9)
* Браузер: Chrome Версия 86.0.4240.75 (Официальная сборка), (64 бит)

#### Скриншоты

![image](https://user-images.githubusercontent.com/54333751/95914670-bf4e9180-0dae-11eb-8b00-d2efdc08a46c.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
