### ISSUE TITLE
Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение.

### ISSUE THREAD

**Issue by balrom1981** [netology-code/git-homeworks#25]
## Шаги по воспроизведению
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат:**
Текст не наезжает на изображение

**Фактический результат:**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
* Устройство: iPhone SE (iOS 14.2)
* Браузер: Chrome (70.0.3538.75)

@solarrust

**Скриншот**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/75252078/101377769-51f94180-38c3-11eb-8ab6-e1996489b2c9.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
