### ISSUE TITLE
Форма обратной связи слишком сжата.

### ISSUE THREAD

**Issue by balrom1981** [netology-code/git-homeworks#26]
## Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
1. Открыть форму обратной связи

**Ожидаемый результат**
Текст не сжат, удобен для прочтения, без переноса слов

**Фактический результат**
Текст слишком сжат по краям, слова не помещаются полностью на строки (см. скриншот)

**Программное окружение**
* Устройство: iPhone SE (iOS 14.2)
* Браузер: Chrome (70.0.3538.75)

@solarrust

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/75252078/101380069-1a3fc900-38c6-11eb-9ea8-6d4195e595a6.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
