### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by troffimovka** [netology-code/git-homeworks#27]
@solarrust
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**
Текст не наезжает на изображение

**Фактический результат**
Текст наезжает на изображение (см. скриншот)

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
![3-2](https://user-images.githubusercontent.com/46753604/104177358-adb26f80-5419-11eb-8f90-5bbcf8ad2fcd.png)

Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
