### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by troffimovka** [netology-code/git-homeworks#28]
@solarrust
**Форма обратной связи слишком сжата**

**Шаги по воспроизведению**

- Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
- Пролистать страницу до блока "Форма обратной связи"

**Ожидаемый результат**
Форма обратной связи выглядит корректно

**Фактический результат**
Форма обратной связи слишком сжата

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![3-2-2](https://user-images.githubusercontent.com/46753604/104177881-89a35e00-541a-11eb-91c1-c4c5f8d2f935.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
