### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by asenok152** [netology-code/git-homeworks#3]
@solarrust 
Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению
Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
Ожидаемый результат
Текст не наезжает на изображение

Фактический результат
Текст наезжает на изображение (см. скриншот)

Программное окружение
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)
![скрин](https://user-images.githubusercontent.com/58488845/70396063-6ee00800-1a16-11ea-949d-e89d3781e0bb.png)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
