### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by JulKos** [netology-code/git-homeworks#47]
### Описание проблемы

Форма обратной связи. Контент в форме обратной связи отображается некорректно за счет слишком сжатых границ формы.

**Шаги по воспроизведению**
1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Открыть форму обратной связи
3. Осмотреться

**Ожидаемый результат**
Размеры формы обратной связи соответствуют дизайну: форма не сжата, границы формы не выходят за пределы экрана.

**Фактический результат**
Форма обратной связи слишком сжата.

**Программное окружение**
Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

_Скриншоты_
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/65012561/122353003-4cf30a00-cf58-11eb-8c3e-8bb3a7a2c329.png)

@solarrust

**Comment by solarrust** [comment]
@JulKos не в том репозитории создаёте задачи.
