### ISSUE TITLE
Текст наезжает на изображение

### ISSUE THREAD

**Issue by LiziMit** [netology-code/git-homeworks#53]
**Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение**

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://user-images.githubusercontent.com/85961076/128604520-110eb517-3eb2-4e1a-8414-3908ecbac279.png)

@solarrust

**Comment by solarrust** [comment]
Не тот репозиторий.
