### ISSUE TITLE
Узкое окно для текста

### ISSUE THREAD

**Issue by LiziMit** [netology-code/git-homeworks#54]
**Главная страница. Текстовый блок "Оставайтесь на связи..." плохо смотрится в этом окне**

**Шаги по воспроизведению**

Открыть главную страницу веб-сайта

1. NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Оставайтесь на связи..."

**Ожидаемый результат**

Размер окна будет лаконично вмещать в себе необходимый текст.

**Фактический результат**

Узкое окно, текст выглядит разбито и кучно (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)
- Браузер: Chrome (70.0.3538.75)

**Скриншоты**
![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/85961076/128604651-ee8a2009-202e-49fa-acec-bae7c34cf1bb.png)

@solarrust

**Comment by solarrust** [comment]
Не тот репозиторий.
