### ISSUE TITLE
Мобильная версия. Главная страница. Текст наезжает на изображение.

### ISSUE THREAD

**Issue by safaleks** [netology-code/git-homeworks#55]
# Описание проблемы
#### Шаги по воспроизведению
1) Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2) Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат
Текст не наезжает на изображение

#### Фактический результат
Текст наезжает на изображение (см. скриншот)

#### Программное окружение
* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)
Скриншоты
![](https://camo.githubusercontent.com/e60494acb1cedbd04df029d249b408c91cec9268f2cfe98a6d3f9b5bb3d52cb3/68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67)
@solarrust

**Comment by solarrust** [comment]
Не тот репозиторий
